services:
  - type: web
    name: met-hub
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn MET.wsgi:application
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
